import type { GrammarSeed } from './grammarTemplates';

export const cultureQuestionSeeds: GrammarSeed[] = [
  {
    id: 'culture-01',
    objectiveCode: 'C-01',
    difficulty: 3,
    promptText: 'Which classroom approach best reflects respect for diverse Spanish-speaking communities?',
    choices: [
      'Present regional varieties as legitimate forms of Spanish with different contexts of use.',
      'Teach that one country has the only correct Spanish.',
      'Avoid discussing language variation at all.',
      'Use stereotypes to make vocabulary easier to remember.',
    ],
    correctIndex: 0,
    explanationText: 'Spanish varies by region and community; effective teaching validates variation while teaching context and register.',
    tags: ['cultural perspectives', 'language variation'],
  },
  {
    id: 'culture-02',
    objectiveCode: 'C-02',
    difficulty: 3,
    promptText: 'A reading mentions that a community celebrates both local and national traditions. What is the best interpretation?',
    choices: [
      'Cultural identity can be layered and shaped by region, nation, family, and migration.',
      'People can have only one cultural identity.',
      'Local traditions are never important.',
      'National traditions are identical in every household.',
    ],
    correctIndex: 0,
    explanationText: 'A nuanced cultural comparison recognizes overlapping identities and avoids one-dimensional claims.',
    tags: ['cultural comparison', 'identity'],
  },
  {
    id: 'culture-03',
    objectiveCode: 'C-03',
    difficulty: 4,
    promptText: 'Which statement about bilingual education is most accurate?',
    choices: [
      'Programs vary widely and may support content learning, biliteracy, and family engagement.',
      'All bilingual programs have the same goals and structure.',
      'Bilingual students must stop using their home language to learn English.',
      'Family language practices are irrelevant to school learning.',
    ],
    correctIndex: 0,
    explanationText: 'Bilingual education is not a single model; strong programs can support academic and linguistic development.',
    tags: ['education', 'bilingualism'],
  },
  {
    id: 'culture-04',
    objectiveCode: 'C-04',
    difficulty: 2,
    promptText: 'A student uses "vos" when speaking about family in parts of Central America. What should a teacher understand?',
    choices: [
      'Voseo is a legitimate regional form in several Spanish-speaking communities.',
      'The student is automatically using incorrect Spanish.',
      'Voseo is used only in written legal documents.',
      'Voseo proves the student cannot use formal register.',
    ],
    correctIndex: 0,
    explanationText: 'Voseo is part of regional Spanish in several areas and can be discussed as language variation.',
    tags: ['language variation', 'register'],
  },
  {
    id: 'culture-05',
    objectiveCode: 'C-05',
    difficulty: 3,
    promptText: 'Which comparison of celebrations is most appropriate for an educator?',
    choices: [
      'Compare purposes, practices, and meanings while noting variation within communities.',
      'Rank celebrations from most to least authentic.',
      'Treat every Spanish-speaking country as having identical traditions.',
      'Avoid student perspectives because only textbooks matter.',
    ],
    correctIndex: 0,
    explanationText: 'Cultural comparison should be respectful, evidence-based, and attentive to internal diversity.',
    tags: ['cultural comparison', 'teaching'],
  },
  {
    id: 'culture-06',
    objectiveCode: 'C-06',
    difficulty: 4,
    promptText: 'A text describes public murals as preserving neighborhood memory. Which lens is most useful?',
    choices: [
      'Art can communicate history, identity, and civic claims in public space.',
      'Murals are only decoration and never historical.',
      'Public art has the same meaning for every viewer.',
      'Neighborhood memory is unrelated to cultural expression.',
    ],
    correctIndex: 0,
    explanationText: 'Public art can carry layered meanings connected to history, identity, and community voice.',
    tags: ['art', 'community', 'history'],
  },
  {
    id: 'culture-07',
    objectiveCode: 'C-07',
    difficulty: 3,
    promptText: 'Which practice best supports heritage speakers in a Spanish class?',
    choices: [
      'Build on existing oral skills while teaching academic registers and literacy.',
      'Assume heritage speakers need no instruction.',
      'Discourage students from sharing home language experiences.',
      'Grade only accent and ignore written development.',
    ],
    correctIndex: 0,
    explanationText: 'Heritage speakers often benefit from instruction that values existing skills and expands literacy and register control.',
    tags: ['heritage learners', 'pedagogy'],
  },
  {
    id: 'culture-08',
    objectiveCode: 'C-08',
    difficulty: 2,
    promptText: 'Why might a teacher include authentic community announcements in class?',
    choices: [
      'They show language used for real purposes and connect learning to community contexts.',
      'They replace all grammar instruction permanently.',
      'They are useful only if every word is unfamiliar.',
      'They prove one dialect is better than another.',
    ],
    correctIndex: 0,
    explanationText: 'Community texts support practical comprehension and cultural context without replacing other instruction.',
    tags: ['authentic texts', 'community'],
  },
  {
    id: 'culture-09',
    objectiveCode: 'C-09',
    difficulty: 4,
    promptText: 'Which statement about migration narratives is most responsible?',
    choices: [
      'They should be approached as varied individual and community experiences, not a single story.',
      'They all follow the same pattern.',
      'They should be avoided because they cannot be discussed respectfully.',
      'They are relevant only to geography, not language.',
    ],
    correctIndex: 0,
    explanationText: 'Migration experiences vary widely and should be treated with care and specificity.',
    tags: ['migration', 'identity'],
  },
  {
    id: 'culture-10',
    objectiveCode: 'C-10',
    difficulty: 3,
    promptText: 'A lesson compares forms of address such as "tu," "usted," and "vos." What concept is central?',
    choices: [
      'Register, relationship, region, and communicative context influence address forms.',
      'Only age determines pronoun choice.',
      'Address forms are random and cannot be taught.',
      'Formal pronouns are never used in Spanish.',
    ],
    correctIndex: 0,
    explanationText: 'Address forms depend on social relationships, region, register, and context.',
    tags: ['register', 'pronouns', 'culture'],
  },
  {
    id: 'culture-11',
    objectiveCode: 'C-11',
    difficulty: 4,
    promptText: 'Which response best avoids a shallow cultural claim about food?',
    choices: [
      'Discuss regional ingredients, history, family practices, and contemporary variation.',
      'Say that everyone in a country eats the same dish every day.',
      'Use one food as proof of national personality.',
      'Avoid context and focus only on memorizing recipe names.',
    ],
    correctIndex: 0,
    explanationText: 'Food practices are varied and meaningful; thoughtful teaching avoids stereotypes.',
    tags: ['food', 'regional culture'],
  },
  {
    id: 'culture-12',
    objectiveCode: 'C-12',
    difficulty: 3,
    promptText: 'Why is it useful to study music in Spanish-speaking communities?',
    choices: [
      'Music can reflect language, history, migration, social change, and local creativity.',
      'Music is culturally neutral and has no context.',
      'Only one music style exists in Spanish.',
      'Lyrics should never be discussed as texts.',
    ],
    correctIndex: 0,
    explanationText: 'Music can be a rich cultural text connected to multiple social and historical contexts.',
    tags: ['music', 'culture'],
  },
  {
    id: 'culture-13',
    objectiveCode: 'C-13',
    difficulty: 5,
    promptText: 'A student asks why some communities maintain Indigenous languages alongside Spanish. What is the strongest response?',
    choices: [
      'Multilingual practices reflect history, identity, rights, education, and community continuity.',
      'Indigenous languages are simply old Spanish dialects.',
      'Only Spanish has cultural value in Latin America.',
      'Multilingualism always prevents academic learning.',
    ],
    correctIndex: 0,
    explanationText: 'Many communities maintain Indigenous languages as living languages connected to identity and rights.',
    tags: ['multilingualism', 'Indigenous languages'],
  },
  {
    id: 'culture-14',
    objectiveCode: 'C-14',
    difficulty: 3,
    promptText: 'Which source would best support a lesson on contemporary community perspectives?',
    choices: [
      'Recent local interviews or community publications with appropriate consent and context.',
      'An anonymous stereotype from social media.',
      'A single outdated travel slogan.',
      'A fictional claim presented as fact.',
    ],
    correctIndex: 0,
    explanationText: 'Responsible cultural teaching uses current, contextualized, and ethically sourced materials.',
    tags: ['sources', 'community'],
  },
  {
    id: 'culture-15',
    objectiveCode: 'C-15',
    difficulty: 2,
    promptText: 'Which teacher statement best frames cultural comparison?',
    choices: [
      'Let us compare practices and the meanings people give them in specific contexts.',
      'Let us decide which culture is more advanced.',
      'Let us ignore differences because they are uncomfortable.',
      'Let us assume all families do the same thing.',
    ],
    correctIndex: 0,
    explanationText: 'Cultural comparison should examine practices, products, and perspectives respectfully.',
    tags: ['cultural comparison', 'pedagogy'],
  },
  {
    id: 'culture-16',
    objectiveCode: 'C-16',
    difficulty: 4,
    promptText: 'What is an accurate statement about code-switching?',
    choices: [
      'It can be a rule-governed bilingual practice shaped by audience, identity, and context.',
      'It always shows confusion.',
      'It is never used by fluent bilingual speakers.',
      'It has no communicative purpose.',
    ],
    correctIndex: 0,
    explanationText: 'Code-switching is often systematic and meaningful, not simply an error.',
    tags: ['bilingualism', 'sociolinguistics'],
  },
  {
    id: 'culture-17',
    objectiveCode: 'C-17',
    difficulty: 3,
    promptText: 'Which activity best connects language and civic life?',
    choices: [
      'Analyze a bilingual voter information flyer for audience, purpose, and register.',
      'Memorize a list of capitals without context.',
      'Translate random sentences without audience.',
      'Avoid public texts because they are not literary.',
    ],
    correctIndex: 0,
    explanationText: 'A bilingual civic flyer shows language used for public participation and audience-aware communication.',
    tags: ['civic life', 'authentic text'],
  },
  {
    id: 'culture-18',
    objectiveCode: 'C-18',
    difficulty: 3,
    promptText: 'Which observation about family terms is most useful?',
    choices: [
      'Terms and expectations vary by community, context, and individual family practice.',
      'Every family uses exactly the same terms.',
      'Family vocabulary has no cultural dimension.',
      'Only dictionary definitions matter in communication.',
    ],
    correctIndex: 0,
    explanationText: 'Family language is culturally meaningful and variable; context matters.',
    tags: ['family', 'vocabulary'],
  },
  {
    id: 'culture-19',
    objectiveCode: 'C-19',
    difficulty: 4,
    promptText: 'Why might a teacher discuss translation choices rather than one-word equivalents only?',
    choices: [
      'Meaning depends on context, register, audience, and cultural expectations.',
      'Every word has exactly one permanent equivalent.',
      'Translation never involves interpretation.',
      'Register is irrelevant in bilingual communication.',
    ],
    correctIndex: 0,
    explanationText: 'Translation requires contextual judgment and awareness of register and audience.',
    tags: ['translation', 'register'],
  },
  {
    id: 'culture-20',
    objectiveCode: 'C-20',
    difficulty: 2,
    promptText: 'Which classroom norm supports respectful cultural discussion?',
    choices: [
      'Use evidence, avoid generalizations, and allow people to speak from varied experiences.',
      'Ask one student to represent an entire culture.',
      'Treat stereotypes as harmless shortcuts.',
      'Discourage questions about context.',
    ],
    correctIndex: 0,
    explanationText: 'Respectful discussion depends on evidence, care, and avoiding tokenizing students.',
    tags: ['classroom culture', 'discussion'],
  },
  {
    id: 'culture-21',
    objectiveCode: 'C-21',
    difficulty: 4,
    promptText: 'A text describes remittances in a migration context. Which interpretation is most complete?',
    choices: [
      'They can reflect family support, economic ties, and transnational relationships.',
      'They are only gifts with no social meaning.',
      'They prove families are disconnected.',
      'They are unrelated to culture or economics.',
    ],
    correctIndex: 0,
    explanationText: 'Remittances may connect economic, family, and transnational dimensions.',
    tags: ['migration', 'economics', 'family'],
  },
  {
    id: 'culture-22',
    objectiveCode: 'C-22',
    difficulty: 3,
    promptText: 'Which description of Spanish-speaking populations in the United States is most accurate?',
    choices: [
      'They are diverse in national origin, race, region, generation, and language background.',
      'They all share the same immigration history.',
      'They all speak Spanish in the same way.',
      'They are unrelated to U.S. civic and cultural life.',
    ],
    correctIndex: 0,
    explanationText: 'Spanish-speaking communities in the United States are highly diverse across many dimensions.',
    tags: ['United States', 'diversity'],
  },
  {
    id: 'culture-23',
    objectiveCode: 'C-23',
    difficulty: 4,
    promptText: 'Which question best encourages cultural inquiry?',
    choices: [
      'How do different people in this community describe the meaning of this practice?',
      'What is the single correct opinion for all members of this culture?',
      'Which group is better?',
      'How can we avoid learning context?',
    ],
    correctIndex: 0,
    explanationText: 'Cultural inquiry asks about meanings, perspectives, and variation.',
    tags: ['inquiry', 'perspectives'],
  },
  {
    id: 'culture-24',
    objectiveCode: 'C-24',
    difficulty: 3,
    promptText: 'Why might a teacher pair a literary text with historical background?',
    choices: [
      'Context can help students understand references, themes, and author choices.',
      'Context replaces reading the text.',
      'Literature never reflects historical moments.',
      'Background information should always be memorized without discussion.',
    ],
    correctIndex: 0,
    explanationText: 'Historical background can support deeper literary interpretation without replacing textual analysis.',
    tags: ['literature', 'history'],
  },
  {
    id: 'culture-25',
    objectiveCode: 'C-25',
    difficulty: 3,
    promptText: 'Which statement about holidays is appropriate?',
    choices: [
      'Holidays may be observed differently by region, family, religion, and personal choice.',
      'Everyone in a country celebrates every holiday the same way.',
      'Holidays are useful only for decorations.',
      'Students should be asked to speak for all people who share a background.',
    ],
    correctIndex: 0,
    explanationText: 'Holiday practices vary, and instruction should avoid assuming uniform participation.',
    tags: ['holidays', 'variation'],
  },
  {
    id: 'culture-26',
    objectiveCode: 'C-26',
    difficulty: 4,
    promptText: 'What is a thoughtful way to discuss dialect features such as aspiration of /s/?',
    choices: [
      'Explain them as systematic phonological variation found in particular regions and contexts.',
      'Label them lazy pronunciation.',
      'Ignore them because listening exams never include variation.',
      'Teach students that only spelling matters in speech.',
    ],
    correctIndex: 0,
    explanationText: 'Dialect features are systematic and should be treated as legitimate variation.',
    tags: ['linguistics', 'phonology'],
  },
  {
    id: 'culture-27',
    objectiveCode: 'C-27',
    difficulty: 5,
    promptText: 'Which lesson objective integrates culture and language most effectively?',
    choices: [
      'Students will analyze how formal requests change across audiences in community emails.',
      'Students will memorize one greeting for every situation.',
      'Students will rank accents by correctness.',
      'Students will avoid all authentic texts.',
    ],
    correctIndex: 0,
    explanationText: 'The objective connects register, audience, authentic communication, and cultural context.',
    tags: ['register', 'authentic communication'],
  },
  {
    id: 'culture-28',
    objectiveCode: 'C-28',
    difficulty: 2,
    promptText: 'Which is a respectful classroom use of student cultural knowledge?',
    choices: [
      'Invite voluntary connections while making clear no student must represent a group.',
      'Require one student to confirm every cultural fact.',
      'Avoid student voices entirely.',
      'Correct home experiences that differ from the textbook.',
    ],
    correctIndex: 0,
    explanationText: 'Students may share voluntarily, but no student should be tokenized as a representative.',
    tags: ['pedagogy', 'student identity'],
  },
  {
    id: 'culture-29',
    objectiveCode: 'C-29',
    difficulty: 4,
    promptText: 'A class studies a newspaper editorial and a personal letter about the same issue. What comparison is most useful?',
    choices: [
      'Audience, purpose, register, evidence, and point of view.',
      'Only the number of words in each text.',
      'Which author has a nicer name.',
      'Whether both texts use the same font.',
    ],
    correctIndex: 0,
    explanationText: 'Text comparisons should consider communicative context and rhetorical choices.',
    tags: ['text analysis', 'register'],
  },
  {
    id: 'culture-30',
    objectiveCode: 'C-30',
    difficulty: 3,
    promptText: 'Which statement about cultural products is strongest?',
    choices: [
      'Products such as books, murals, music, and foods can reveal perspectives when studied in context.',
      'Products always have one obvious meaning.',
      'Products are separate from practices and perspectives.',
      'Products should be used only as decoration.',
    ],
    correctIndex: 0,
    explanationText: 'The products-practices-perspectives framework works best when products are contextualized.',
    tags: ['products practices perspectives', 'culture'],
  },
];
