export interface GrammarSeed {
  id: string;
  objectiveCode: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  promptText: string;
  choices: string[];
  correctIndex: number;
  explanationText: string;
  tags: string[];
}

export const grammarQuestionSeeds: GrammarSeed[] = [
  {
    id: 'subj-01',
    objectiveCode: 'G-01',
    difficulty: 3,
    promptText: 'Choose the best completion: Es importante que los estudiantes ___ las instrucciones antes de empezar.',
    choices: ['lean', 'leen', 'leyeron', 'leeran'],
    correctIndex: 0,
    explanationText: 'After impersonal expressions such as "es importante que," Spanish normally uses the present subjunctive.',
    tags: ['subjunctive', 'present subjunctive'],
  },
  {
    id: 'subj-02',
    objectiveCode: 'G-01',
    difficulty: 4,
    promptText: 'Choose the best completion: Buscamos una actividad que ___ a todos los niveles.',
    choices: ['sirva', 'sirve', 'sirvio', 'servira'],
    correctIndex: 0,
    explanationText: 'A non-specific or desired antecedent after "buscar" triggers the subjunctive: que sirva.',
    tags: ['subjunctive', 'relative clause'],
  },
  {
    id: 'subj-03',
    objectiveCode: 'G-01',
    difficulty: 3,
    promptText: 'Choose the best completion: Ojala que la reunion ___ puntualmente.',
    choices: ['empiece', 'empieza', 'empezo', 'empezaba'],
    correctIndex: 0,
    explanationText: '"Ojala que" expresses a wish, so the present subjunctive form "empiece" is needed.',
    tags: ['subjunctive', 'wishes'],
  },
  {
    id: 'subj-04',
    objectiveCode: 'G-01',
    difficulty: 4,
    promptText: 'Choose the best completion: Aunque ___ frio, la clase saldra al jardin si no llueve.',
    choices: ['haga', 'hace', 'hizo', 'haria'],
    correctIndex: 0,
    explanationText: 'When "aunque" refers to a hypothetical future condition, Spanish uses the subjunctive.',
    tags: ['subjunctive', 'concession'],
  },
  {
    id: 'subj-05',
    objectiveCode: 'G-01',
    difficulty: 5,
    promptText: 'Choose the best completion: No habia nadie que ___ explicar el cambio de horario.',
    choices: ['pudiera', 'podia', 'puede', 'podra'],
    correctIndex: 0,
    explanationText: 'A nonexistent antecedent in the past calls for the imperfect subjunctive: pudiera.',
    tags: ['imperfect subjunctive', 'relative clause'],
  },
  {
    id: 'pret-imp-01',
    objectiveCode: 'G-02',
    difficulty: 2,
    promptText: 'Choose the best completion: Cuando era nina, Ana ___ al parque todos los domingos.',
    choices: ['iba', 'fue', 'iria', 'vaya'],
    correctIndex: 0,
    explanationText: 'The imperfect describes habitual past actions, such as going to the park every Sunday.',
    tags: ['preterite imperfect', 'habitual past'],
  },
  {
    id: 'pret-imp-02',
    objectiveCode: 'G-02',
    difficulty: 2,
    promptText: 'Choose the best completion: Ayer la directora ___ la noticia durante la asamblea.',
    choices: ['anuncio', 'anunciaba', 'anunciara', 'anuncie'],
    correctIndex: 0,
    explanationText: 'The preterite presents a completed past action at a specific time: ayer anuncio.',
    tags: ['preterite', 'completed action'],
  },
  {
    id: 'pret-imp-03',
    objectiveCode: 'G-02',
    difficulty: 3,
    promptText: 'Choose the best completion: Yo ___ la tarea cuando sono el telefono.',
    choices: ['hacia', 'hice', 'hare', 'haga'],
    correctIndex: 0,
    explanationText: 'The imperfect gives the background action interrupted by the preterite action "sono."',
    tags: ['preterite imperfect', 'interruption'],
  },
  {
    id: 'pret-imp-04',
    objectiveCode: 'G-02',
    difficulty: 4,
    promptText: 'Choose the best completion: El verano pasado mis primos ___ a Puerto Rico por primera vez.',
    choices: ['viajaron', 'viajaban', 'viajen', 'viajarian'],
    correctIndex: 0,
    explanationText: 'A completed trip during a defined past period takes the preterite.',
    tags: ['preterite', 'travel'],
  },
  {
    id: 'pret-imp-05',
    objectiveCode: 'G-02',
    difficulty: 3,
    promptText: 'Choose the best completion: La sala ___ silenciosa mientras los estudiantes leian.',
    choices: ['estaba', 'estuvo', 'este', 'estaria'],
    correctIndex: 0,
    explanationText: 'The imperfect describes the ongoing background condition of the room.',
    tags: ['imperfect', 'description'],
  },
  {
    id: 'ser-estar-01',
    objectiveCode: 'G-03',
    difficulty: 1,
    promptText: 'Choose the best completion: La profesora ___ de Chile.',
    choices: ['es', 'esta', 'fue estando', 'sea estar'],
    correctIndex: 0,
    explanationText: 'Origin is expressed with "ser": es de Chile.',
    tags: ['ser estar', 'origin'],
  },
  {
    id: 'ser-estar-02',
    objectiveCode: 'G-03',
    difficulty: 2,
    promptText: 'Choose the best completion: Los cuadernos ___ sobre la mesa.',
    choices: ['estan', 'son', 'fueron', 'seran'],
    correctIndex: 0,
    explanationText: 'Location of objects is expressed with "estar": estan sobre la mesa.',
    tags: ['ser estar', 'location'],
  },
  {
    id: 'ser-estar-03',
    objectiveCode: 'G-03',
    difficulty: 3,
    promptText: 'Choose the best completion: La reunion ___ en la biblioteca a las tres.',
    choices: ['es', 'esta', 'estaba siendo', 'sea estando'],
    correctIndex: 0,
    explanationText: 'Scheduled events use "ser" for location and time.',
    tags: ['ser estar', 'events'],
  },
  {
    id: 'ser-estar-04',
    objectiveCode: 'G-03',
    difficulty: 3,
    promptText: 'Choose the best completion: Miguel ___ preocupado porque perdio su cuaderno.',
    choices: ['esta', 'es', 'fue', 'sera'],
    correctIndex: 0,
    explanationText: 'A temporary emotional state is expressed with "estar."',
    tags: ['ser estar', 'emotion'],
  },
  {
    id: 'ser-estar-05',
    objectiveCode: 'G-03',
    difficulty: 4,
    promptText: 'Choose the best completion: La explicacion de la maestra ___ clara y util.',
    choices: ['fue', 'estuvo', 'estaba siendo', 'este'],
    correctIndex: 0,
    explanationText: 'Evaluation of an event or explanation commonly uses "ser"; "fue clara" judges the explanation.',
    tags: ['ser estar', 'evaluation'],
  },
  {
    id: 'por-para-01',
    objectiveCode: 'G-04',
    difficulty: 2,
    promptText: 'Choose the best completion: Este folleto es ___ los padres de estudiantes nuevos.',
    choices: ['para', 'por', 'con', 'desde'],
    correctIndex: 0,
    explanationText: '"Para" indicates intended recipient or purpose.',
    tags: ['por para', 'recipient'],
  },
  {
    id: 'por-para-02',
    objectiveCode: 'G-04',
    difficulty: 3,
    promptText: 'Choose the best completion: Gracias ___ ayudarme con la pronunciacion.',
    choices: ['por', 'para', 'a', 'desde'],
    correctIndex: 0,
    explanationText: 'Spanish uses "gracias por" before the reason for thanks.',
    tags: ['por para', 'idiom'],
  },
  {
    id: 'por-para-03',
    objectiveCode: 'G-04',
    difficulty: 3,
    promptText: 'Choose the best completion: Salimos ___ la escuela a las siete y media.',
    choices: ['para', 'por', 'sobre', 'contra'],
    correctIndex: 0,
    explanationText: '"Salir para" indicates destination or direction toward a place.',
    tags: ['por para', 'destination'],
  },
  {
    id: 'por-para-04',
    objectiveCode: 'G-04',
    difficulty: 4,
    promptText: 'Choose the best completion: Caminamos ___ el parque antes de llegar al museo.',
    choices: ['por', 'para', 'a', 'de'],
    correctIndex: 0,
    explanationText: '"Por" can indicate movement through or along a place.',
    tags: ['por para', 'movement'],
  },
  {
    id: 'por-para-05',
    objectiveCode: 'G-04',
    difficulty: 4,
    promptText: 'Choose the best completion: Necesito terminar el informe ___ manana.',
    choices: ['para', 'por', 'desde', 'en'],
    correctIndex: 0,
    explanationText: '"Para" marks a deadline: para manana.',
    tags: ['por para', 'deadline'],
  },
  {
    id: 'pronouns-01',
    objectiveCode: 'G-05',
    difficulty: 3,
    promptText: 'Choose the best replacement for the underlined idea: Compre los boletos para mis padres.',
    choices: ['Se los compre.', 'Los se compre.', 'Les los compre.', 'Se les compre los.'],
    correctIndex: 0,
    explanationText: 'With both indirect and direct object pronouns, "les" changes to "se": se los compre.',
    tags: ['object pronouns', 'indirect object'],
  },
  {
    id: 'pronouns-02',
    objectiveCode: 'G-05',
    difficulty: 2,
    promptText: 'Choose the best completion: La tarea, yo ___ entregue ayer.',
    choices: ['la', 'lo', 'le', 'se'],
    correctIndex: 0,
    explanationText: '"La tarea" is feminine singular, so the direct object pronoun is "la."',
    tags: ['direct object pronouns', 'agreement'],
  },
  {
    id: 'pronouns-03',
    objectiveCode: 'G-05',
    difficulty: 3,
    promptText: 'Choose the best completion: A los estudiantes ___ explicamos la actividad.',
    choices: ['les', 'los', 'las', 'se los'],
    correctIndex: 0,
    explanationText: '"A los estudiantes" is the indirect object, so "les" is appropriate.',
    tags: ['indirect object pronouns'],
  },
  {
    id: 'pronouns-04',
    objectiveCode: 'G-05',
    difficulty: 4,
    promptText: 'Choose the correct command with pronouns: Give it to me. (informal)',
    choices: ['Damelo.', 'Me lo da.', 'Dame lo.', 'Lo me da.'],
    correctIndex: 0,
    explanationText: 'In affirmative commands, object pronouns attach to the end: dame + lo = damelo.',
    tags: ['commands', 'object pronouns'],
  },
  {
    id: 'pronouns-05',
    objectiveCode: 'G-05',
    difficulty: 4,
    promptText: 'Choose the best completion: No ___ digas el secreto a nadie.',
    choices: ['se lo', 'lo se', 'le lo', 'lo le'],
    correctIndex: 0,
    explanationText: 'In negative commands, pronouns precede the verb; "le/les" becomes "se" before "lo."',
    tags: ['negative commands', 'object pronouns'],
  },
  {
    id: 'relative-01',
    objectiveCode: 'G-06',
    difficulty: 3,
    promptText: 'Choose the best completion: La escuela ___ visite ayer tiene un programa bilingue.',
    choices: ['que', 'quien', 'cuyo', 'donde que'],
    correctIndex: 0,
    explanationText: '"Que" can introduce a relative clause referring to a thing or place as direct object.',
    tags: ['relative pronouns'],
  },
  {
    id: 'relative-02',
    objectiveCode: 'G-06',
    difficulty: 4,
    promptText: 'Choose the best completion: La autora, ___ libro leimos, visitara la clase.',
    choices: ['cuyo', 'que', 'donde', 'lo que'],
    correctIndex: 0,
    explanationText: '"Cuyo" expresses possession and agrees with the noun that follows: cuyo libro.',
    tags: ['relative pronouns', 'possession'],
  },
  {
    id: 'relative-03',
    objectiveCode: 'G-06',
    difficulty: 4,
    promptText: 'Choose the best completion: El parque ___ jugabamos de ninos ya tiene una biblioteca pequena.',
    choices: ['donde', 'quien', 'cuyo', 'lo que'],
    correctIndex: 0,
    explanationText: '"Donde" refers to a place in a relative clause.',
    tags: ['relative pronouns', 'place'],
  },
  {
    id: 'relative-04',
    objectiveCode: 'G-06',
    difficulty: 5,
    promptText: 'Choose the best completion: ___ me preocupa es la falta de tiempo para revisar.',
    choices: ['Lo que', 'Quien', 'Cuyo', 'Donde'],
    correctIndex: 0,
    explanationText: '"Lo que" means "what" or "the thing that" when referring to an idea.',
    tags: ['relative pronouns', 'abstract reference'],
  },
  {
    id: 'relative-05',
    objectiveCode: 'G-06',
    difficulty: 3,
    promptText: 'Choose the best completion: La estudiante con ___ hable ayer quiere practicar mas.',
    choices: ['quien', 'que', 'cuyo', 'donde'],
    correctIndex: 0,
    explanationText: 'After a preposition and referring to a person, "quien" is appropriate.',
    tags: ['relative pronouns', 'person'],
  },
  {
    id: 'commands-01',
    objectiveCode: 'G-07',
    difficulty: 2,
    promptText: 'Choose the correct formal command: Please open the book.',
    choices: ['Abra el libro, por favor.', 'Abre el libro, por favor.', 'Abres el libro, por favor.', 'Abrio el libro, por favor.'],
    correctIndex: 0,
    explanationText: 'The formal usted command for abrir is "abra."',
    tags: ['commands', 'formal register'],
  },
  {
    id: 'commands-02',
    objectiveCode: 'G-07',
    difficulty: 3,
    promptText: 'Choose the correct negative informal command: Do not write on the board.',
    choices: ['No escribas en la pizarra.', 'No escribe en la pizarra.', 'No escribes en la pizarra.', 'No escribir en la pizarra.'],
    correctIndex: 0,
    explanationText: 'Negative tu commands use the present subjunctive form: no escribas.',
    tags: ['commands', 'negative command'],
  },
  {
    id: 'commands-03',
    objectiveCode: 'G-07',
    difficulty: 3,
    promptText: 'Choose the best classroom direction for ustedes: Read the paragraph.',
    choices: ['Lean el parrafo.', 'Leen el parrafo.', 'Lee el parrafo.', 'Leyo el parrafo.'],
    correctIndex: 0,
    explanationText: 'The ustedes command uses the present subjunctive form: lean.',
    tags: ['commands', 'classroom'],
  },
  {
    id: 'commands-04',
    objectiveCode: 'G-07',
    difficulty: 4,
    promptText: 'Choose the correct affirmative informal command: Tell me the answer.',
    choices: ['Dime la respuesta.', 'Me di la respuesta.', 'Dices me la respuesta.', 'Digas la respuesta.'],
    correctIndex: 0,
    explanationText: 'The irregular affirmative tu command for decir is "di"; with "me" attached it becomes "dime."',
    tags: ['commands', 'irregular command'],
  },
  {
    id: 'commands-05',
    objectiveCode: 'G-07',
    difficulty: 5,
    promptText: 'Choose the correct negative command: Do not give it to them.',
    choices: ['No se lo des.', 'No daselo.', 'No les lo da.', 'No dales lo.'],
    correctIndex: 0,
    explanationText: 'Negative commands place pronouns before the verb, and "les lo" becomes "se lo."',
    tags: ['commands', 'pronouns'],
  },
  {
    id: 'agreement-01',
    objectiveCode: 'G-08',
    difficulty: 1,
    promptText: 'Choose the correct adjective agreement: las ventanas ___.',
    choices: ['abiertas', 'abiertos', 'abierta', 'abierto'],
    correctIndex: 0,
    explanationText: '"Ventanas" is feminine plural, so the adjective is "abiertas."',
    tags: ['agreement', 'adjectives'],
  },
  {
    id: 'agreement-02',
    objectiveCode: 'G-08',
    difficulty: 2,
    promptText: 'Choose the best completion: Hay veintiun ___ en la lista.',
    choices: ['estudiantes', 'estudiante', 'estudiantas', 'estudiantos'],
    correctIndex: 0,
    explanationText: 'With a masculine plural noun after veintiun, the plural noun "estudiantes" is used.',
    tags: ['agreement', 'numbers'],
  },
  {
    id: 'agreement-03',
    objectiveCode: 'G-08',
    difficulty: 3,
    promptText: 'Choose the correct sentence.',
    choices: [
      'La mayoria de los estudiantes llego temprano.',
      'La mayoria de los estudiantes llegaron temprano es siempre obligatorio.',
      'La mayoria llegaron temprano de los estudiantes.',
      'Los mayoria de estudiantes llego temprano.',
    ],
    correctIndex: 0,
    explanationText: 'Collective nouns such as "la mayoria" often take singular agreement in formal Spanish.',
    tags: ['agreement', 'subject verb'],
  },
  {
    id: 'agreement-04',
    objectiveCode: 'G-08',
    difficulty: 4,
    promptText: 'Choose the best completion: El agua fria ___ refrescante.',
    choices: ['es', 'son', 'esta son', 'estan'],
    correctIndex: 0,
    explanationText: '"Agua" is grammatically feminine but singular; the verb agrees singular: es.',
    tags: ['agreement', 'gender'],
  },
  {
    id: 'agreement-05',
    objectiveCode: 'G-08',
    difficulty: 3,
    promptText: 'Choose the correct adjective form: un problema ___.',
    choices: ['dificil', 'dificila', 'dificiles', 'dificilo'],
    correctIndex: 0,
    explanationText: 'Adjectives ending in -l generally do not change for gender in the singular.',
    tags: ['agreement', 'adjectives'],
  },
  {
    id: 'accent-01',
    objectiveCode: 'G-09',
    difficulty: 2,
    promptText: 'Choose the word that correctly means "he/she spoke."',
    choices: ['habló', 'hablo', 'hablar', 'hablaba'],
    correctIndex: 0,
    explanationText: 'The preterite third-person singular is written "hablo" with a written accent on the final vowel in standard Spanish.',
    tags: ['accent marks', 'preterite'],
  },
  {
    id: 'accent-02',
    objectiveCode: 'G-09',
    difficulty: 2,
    promptText: 'Choose the question word with the correct accent: ¿___ llegó tarde?',
    choices: ['Por qué', 'Porque', 'Por que', 'Porqué'],
    correctIndex: 0,
    explanationText: 'In direct questions, "por que" is written as the interrogative phrase with an accent on "que" in standard Spanish.',
    tags: ['accent marks', 'questions'],
  },
  {
    id: 'accent-03',
    objectiveCode: 'G-09',
    difficulty: 3,
    promptText: 'Choose the correct sentence.',
    choices: ['Mi hermano estudia inglés y francés.', 'Mi hermano estudia ingles y francès.', 'Mi hermano estudia inglés y frances.', 'Mi hermano estudia ingles y franceses.'],
    correctIndex: 0,
    explanationText: 'In standard Spanish, language names such as ingles and frances carry written accents on the final syllable.',
    tags: ['accent marks', 'vocabulary'],
  },
  {
    id: 'accent-04',
    objectiveCode: 'G-09',
    difficulty: 3,
    promptText: 'Choose the correct distinction.',
    choices: ['tu = your; tú = you', 'tu = always a verb', 'tú = your', 'tu and tú are interchangeable in formal writing'],
    correctIndex: 0,
    explanationText: 'The possessive "tu" has no written accent; the subject pronoun "tú" has a written accent in standard Spanish.',
    tags: ['accent marks', 'homophones'],
  },
  {
    id: 'accent-05',
    objectiveCode: 'G-09',
    difficulty: 4,
    promptText: 'Choose the correct form for the sentence: Quiero saber ___ estudias.',
    choices: ['dónde', 'donde', 'dondequiera', 'adónde only'],
    correctIndex: 0,
    explanationText: 'Indirect questions use interrogative words with written accents in standard Spanish.',
    tags: ['accent marks', 'indirect questions'],
  },
  {
    id: 'idiom-01',
    objectiveCode: 'G-10',
    difficulty: 2,
    promptText: 'Choose the most natural translation: I am hungry.',
    choices: ['Tengo hambre.', 'Soy hambre.', 'Estoy hambre.', 'Hago hambre.'],
    correctIndex: 0,
    explanationText: 'Spanish uses "tener hambre" for being hungry.',
    tags: ['idioms', 'tener expressions'],
  },
  {
    id: 'idiom-02',
    objectiveCode: 'G-10',
    difficulty: 3,
    promptText: 'Choose the most natural translation: It is worth the effort.',
    choices: ['Vale la pena.', 'Tiene la pena.', 'Es la pena.', 'Hace la pena.'],
    correctIndex: 0,
    explanationText: '"Valer la pena" is the idiomatic expression for being worthwhile.',
    tags: ['idioms', 'communication'],
  },
  {
    id: 'idiom-03',
    objectiveCode: 'G-10',
    difficulty: 3,
    promptText: 'Choose the best completion: Para pedir ayuda con cortesia, diga: "___ ayudarme?"',
    choices: ['Podria', 'Puede tu', 'Dame', 'Ayuda ahora'],
    correctIndex: 0,
    explanationText: '"Podria ayudarme?" uses a polite conditional form appropriate for courteous requests.',
    tags: ['register', 'politeness'],
  },
  {
    id: 'idiom-04',
    objectiveCode: 'G-10',
    difficulty: 4,
    promptText: 'Choose the phrase that best fits a formal email closing.',
    choices: ['Atentamente,', 'Nos vemos, bro,', 'Que onda,', 'Chao pues sin nombre,'],
    correctIndex: 0,
    explanationText: '"Atentamente" is a conventional formal closing.',
    tags: ['register', 'email'],
  },
  {
    id: 'idiom-05',
    objectiveCode: 'G-10',
    difficulty: 3,
    promptText: 'Choose the best meaning of "darse cuenta de."',
    choices: ['to realize', 'to give an account literally only', 'to fall down', 'to pay a bill'],
    correctIndex: 0,
    explanationText: '"Darse cuenta de" means to realize or become aware of something.',
    tags: ['idioms', 'meaning'],
  },
  {
    id: 'syntax-01',
    objectiveCode: 'G-11',
    difficulty: 3,
    promptText: 'Choose the sentence with natural Spanish word order.',
    choices: ['Manana vamos a visitar el museo.', 'Vamos manana visitar a el museo.', 'A visitar museo vamos manana.', 'Manana a el museo visitar vamos.'],
    correctIndex: 0,
    explanationText: 'The correct sentence places the time expression naturally and uses "ir a + infinitive."',
    tags: ['syntax', 'word order'],
  },
  {
    id: 'syntax-02',
    objectiveCode: 'G-11',
    difficulty: 4,
    promptText: 'Choose the best completion: Me interesa ___ los estudiantes usan estrategias de lectura.',
    choices: ['como', 'que como', 'lo como que', 'cual de'],
    correctIndex: 0,
    explanationText: 'An indirect question uses "como" to mean "how."',
    tags: ['syntax', 'indirect question'],
  },
  {
    id: 'syntax-03',
    objectiveCode: 'G-11',
    difficulty: 4,
    promptText: 'Choose the sentence that avoids an English-like calque.',
    choices: ['Asisti a la reunion.', 'Asisti la reunion.', 'Atendi la reunion.', 'Estuve asistencia a la reunion.'],
    correctIndex: 0,
    explanationText: '"Asistir a" means to attend; "atender" usually means to serve or attend to someone.',
    tags: ['syntax', 'false cognates'],
  },
  {
    id: 'syntax-04',
    objectiveCode: 'G-11',
    difficulty: 5,
    promptText: 'Choose the best connector: ___ no habia mucho tiempo, terminamos la revision esencial.',
    choices: ['Aunque', 'Porque de', 'Durante que', 'Mientras de'],
    correctIndex: 0,
    explanationText: '"Aunque" introduces a concession: although there was not much time.',
    tags: ['syntax', 'connectors'],
  },
  {
    id: 'syntax-05',
    objectiveCode: 'G-11',
    difficulty: 3,
    promptText: 'Choose the most coherent sentence.',
    choices: ['Despues de leer, los estudiantes discutieron el tema en grupos.', 'Despues leer discutieron tema estudiantes grupos.', 'Los estudiantes despues de el leer tema grupos.', 'Discutieron el despues grupos leer tema.'],
    correctIndex: 0,
    explanationText: 'The correct option uses "despues de + infinitive" and a clear subject-verb-object structure.',
    tags: ['syntax', 'cohesion'],
  },
  {
    id: 'morph-01',
    objectiveCode: 'G-12',
    difficulty: 3,
    promptText: 'Which word contains a prefix meaning "again" or "back"?',
    choices: ['releer', 'feliz', 'mesa', 'rapido'],
    correctIndex: 0,
    explanationText: 'The prefix "re-" in "releer" can mean doing an action again.',
    tags: ['morphology', 'prefixes'],
  },
  {
    id: 'morph-02',
    objectiveCode: 'G-12',
    difficulty: 3,
    promptText: 'What is the function of "-mente" in "claramente"?',
    choices: ['It forms an adverb.', 'It forms a plural noun.', 'It marks future tense.', 'It creates a diminutive.'],
    correctIndex: 0,
    explanationText: 'The suffix "-mente" forms adverbs from many adjectives.',
    tags: ['morphology', 'suffixes'],
  },
  {
    id: 'morph-03',
    objectiveCode: 'G-12',
    difficulty: 4,
    promptText: 'Choose the word that includes a diminutive suffix.',
    choices: ['casita', 'casona', 'casa', 'casar'],
    correctIndex: 0,
    explanationText: '"Casita" uses the diminutive suffix "-ita."',
    tags: ['morphology', 'diminutives'],
  },
  {
    id: 'morph-04',
    objectiveCode: 'G-12',
    difficulty: 4,
    promptText: 'Which pair best shows a verb and a related noun?',
    choices: ['educar / educacion', 'mesa / mesamente', 'azul / azularmente', 'tres / tresacion'],
    correctIndex: 0,
    explanationText: '"Educacion" is a noun related to the verb "educar."',
    tags: ['morphology', 'derivation'],
  },
  {
    id: 'morph-05',
    objectiveCode: 'G-12',
    difficulty: 5,
    promptText: 'In "desconocido," what does the prefix "des-" contribute?',
    choices: ['A negative or reversing meaning', 'A plural meaning', 'A future meaning', 'A question meaning'],
    correctIndex: 0,
    explanationText: 'The prefix "des-" often contributes negation or reversal, as in "desconocido."',
    tags: ['morphology', 'prefixes'],
  },
];
