export interface ListeningSeed {
  id: string;
  objectiveCode: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  script: string;
  mainQuestion: string;
  mainChoices: string[];
  mainCorrectIndex: number;
  mainExplanation: string;
  inferenceQuestion: string;
  inferenceChoices: string[];
  inferenceCorrectIndex: number;
  inferenceExplanation: string;
  tags: string[];
}

export const listeningPromptSeeds: ListeningSeed[] = [
  {
    id: 'school-conference',
    objectiveCode: 'L-01',
    difficulty: 2,
    script:
      'Buenos dias, senora Ruiz. Le llamo de la escuela Lincoln para confirmar la conferencia de manana a las cuatro. La maestra quiere hablar de los avances de Mateo en lectura y tambien de una estrategia para entregar la tarea a tiempo.',
    mainQuestion: 'What is the main purpose of the message?',
    mainChoices: ['To cancel a class trip', 'To confirm a school conference', 'To request medical forms', 'To announce a new textbook'],
    mainCorrectIndex: 1,
    mainExplanation: 'The speaker confirms a parent-teacher conference and mentions topics for the meeting.',
    inferenceQuestion: 'What can be inferred about Mateo?',
    inferenceChoices: [
      'He has stopped attending school.',
      'He needs a new reading teacher.',
      'He is improving but needs help with homework routines.',
      'He will move to another classroom tomorrow.',
    ],
    inferenceCorrectIndex: 2,
    inferenceExplanation: 'The message says Mateo has made progress in reading and needs a strategy for submitting homework on time.',
    tags: ['school', 'family', 'main idea', 'inference'],
  },
  {
    id: 'travel-change',
    objectiveCode: 'L-02',
    difficulty: 3,
    script:
      'Atencion pasajeros con destino a San Juan. Debido a la tormenta, el vuelo 218 saldra de la puerta C12 y no de la B7. La hora de salida sigue siendo las seis y veinte, pero el embarque comenzara diez minutos antes.',
    mainQuestion: 'What change is announced?',
    mainChoices: ['The gate changed.', 'The destination changed.', 'The flight was canceled.', 'The ticket price changed.'],
    mainCorrectIndex: 0,
    mainExplanation: 'The announcement changes the gate from B7 to C12 while keeping the departure time.',
    inferenceQuestion: 'What should passengers do next?',
    inferenceChoices: ['Go to gate C12 soon', 'Ask for a refund', 'Return tomorrow morning', 'Wait at baggage claim'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'Because boarding begins earlier at the new gate, passengers should proceed there soon.',
    tags: ['travel', 'announcement', 'detail', 'inference'],
  },
  {
    id: 'community-festival',
    objectiveCode: 'L-03',
    difficulty: 2,
    script:
      'Este sabado el centro comunitario celebrara una feria de lectura bilingue. Habra cuentos para ninos, intercambio de libros usados y una mesa donde los padres podran inscribirse para clases de ingles por la noche.',
    mainQuestion: 'What event is being described?',
    mainChoices: ['A bilingual reading fair', 'A city council debate', 'A sports tournament', 'A school lunch meeting'],
    mainCorrectIndex: 0,
    mainExplanation: 'The announcement describes a bilingual reading fair with books, stories, and classes for parents.',
    inferenceQuestion: 'Who is one likely audience for this event?',
    inferenceChoices: ['Families in the community', 'Only professional translators', 'Only high school athletes', 'Airline passengers'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'Stories for children and evening classes for parents indicate that local families are a target audience.',
    tags: ['community', 'family', 'education'],
  },
  {
    id: 'classroom-direction',
    objectiveCode: 'L-04',
    difficulty: 1,
    script:
      'Clase, antes de empezar el experimento, pongan los telefonos en silencio, abran el cuaderno en la pagina treinta y dos y trabajen con su companero para completar la primera tabla.',
    mainQuestion: 'What does the teacher ask students to do first?',
    mainChoices: ['Turn in an essay', 'Silence their phones', 'Leave the classroom', 'Read a novel aloud'],
    mainCorrectIndex: 1,
    mainExplanation: 'The first direction is to put phones on silent before opening notebooks and working in pairs.',
    inferenceQuestion: 'What type of activity is likely about to begin?',
    inferenceChoices: ['A science experiment', 'A school concert', 'A lunch order', 'A bus evacuation drill'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'The teacher mentions an experiment and completing a table with a partner.',
    tags: ['classroom', 'directions', 'education'],
  },
  {
    id: 'doctor-appointment',
    objectiveCode: 'L-05',
    difficulty: 3,
    script:
      'Le habla la clinica del barrio. Su cita con la doctora Alvarez sera el jueves a las nueve y media. Si necesita cambiarla, llame antes del miercoles al mediodia para no perder el deposito.',
    mainQuestion: 'What is the caller confirming?',
    mainChoices: ['A pharmacy delivery', 'A medical appointment', 'A language class', 'A job interview'],
    mainCorrectIndex: 1,
    mainExplanation: 'The caller confirms an appointment with Dr. Alvarez and gives rescheduling instructions.',
    inferenceQuestion: 'Why should the listener call before Wednesday noon if plans change?',
    inferenceChoices: ['To avoid losing a deposit', 'To receive a free medicine', 'To change doctors permanently', 'To reserve a parking space'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'The message explicitly says calling after that time may result in losing the deposit.',
    tags: ['appointment', 'community', 'detail'],
  },
  {
    id: 'library-hours',
    objectiveCode: 'L-06',
    difficulty: 2,
    script:
      'La biblioteca publica abrira tarde el lunes por capacitacion del personal. Las puertas abriran a la una de la tarde. Los materiales que vencen ese dia se podran devolver el martes sin multa.',
    mainQuestion: 'What is the main announcement?',
    mainChoices: ['The library is opening late Monday.', 'The library is closing for a month.', 'All fines are increasing.', 'A new branch is opening downtown.'],
    mainCorrectIndex: 0,
    mainExplanation: 'The announcement focuses on delayed Monday hours because of staff training.',
    inferenceQuestion: 'What accommodation is offered to patrons?',
    inferenceChoices: ['Tuesday returns will not be fined.', 'All books may be kept permanently.', 'The library will deliver books home.', 'Training is open to the public.'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'Items due Monday can be returned Tuesday without a fine.',
    tags: ['public announcement', 'library', 'community'],
  },
  {
    id: 'family-plans',
    objectiveCode: 'L-07',
    difficulty: 2,
    script:
      'Marta, no olvides que cenamos en casa de tus tios a las siete. Yo llevo la ensalada y tu papa compro el pastel. Si puedes, pasa por la panaderia y compra pan antes de venir.',
    mainQuestion: 'What is the family planning?',
    mainChoices: ['A dinner at the aunt and uncle house', 'A school performance', 'A trip to the bank', 'A medical exam'],
    mainCorrectIndex: 0,
    mainExplanation: 'The speaker says they will have dinner at the aunt and uncle house at seven.',
    inferenceQuestion: 'What is Marta being asked to do?',
    inferenceChoices: ['Buy bread on the way', 'Bake the cake', 'Cancel the dinner', 'Bring a salad'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'The speaker asks Marta to stop at the bakery and buy bread before arriving.',
    tags: ['family', 'errands', 'daily life'],
  },
  {
    id: 'museum-tour',
    objectiveCode: 'L-08',
    difficulty: 4,
    script:
      'Bienvenidos al museo. La visita guiada sobre arte afrocaribeno comienza en quince minutos en la sala tres. Despues, la curadora respondera preguntas sobre las tecnicas y los contextos historicos de las obras.',
    mainQuestion: 'What will the guided tour focus on?',
    mainChoices: ['Afro-Caribbean art', 'Modern architecture', 'Sports history', 'Children books'],
    mainCorrectIndex: 0,
    mainExplanation: 'The guide names a tour about Afro-Caribbean art in room three.',
    inferenceQuestion: 'What opportunity will visitors have after the tour?',
    inferenceChoices: ['Ask the curator questions', 'Purchase airline tickets', 'Take a cooking exam', 'Vote for a city official'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'The curator will answer questions about techniques and historical contexts.',
    tags: ['culture', 'museum', 'history'],
  },
  {
    id: 'student-project',
    objectiveCode: 'L-09',
    difficulty: 3,
    script:
      'Para el proyecto final, cada grupo debe entrevistar a una persona mayor sobre un cambio importante en el vecindario. Traigan una lista de preguntas el viernes para revisarla antes de hacer la entrevista.',
    mainQuestion: 'What is the assignment?',
    mainChoices: ['Interview an older person about neighborhood change', 'Memorize a poem for Friday', 'Prepare a science fair display', 'Write a restaurant review'],
    mainCorrectIndex: 0,
    mainExplanation: 'Groups must interview an older person about a significant neighborhood change.',
    inferenceQuestion: 'Why should students bring questions on Friday?',
    inferenceChoices: ['So the teacher can review them before the interview', 'So they can avoid doing the interview', 'So the class can vote on grades', 'So they can translate a menu'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'The teacher says the questions will be reviewed before students conduct the interview.',
    tags: ['classroom', 'project', 'interview'],
  },
  {
    id: 'weather-alert',
    objectiveCode: 'L-10',
    difficulty: 3,
    script:
      'El servicio meteorologico informa que habra lluvia intensa esta tarde. Las actividades al aire libre del programa juvenil se trasladan al gimnasio municipal. La hora de recogida no cambia.',
    mainQuestion: 'What is changing because of the weather?',
    mainChoices: ['The activity location', 'The pickup time', 'The program age limit', 'The registration fee'],
    mainCorrectIndex: 0,
    mainExplanation: 'Outdoor youth program activities are moved to the municipal gym.',
    inferenceQuestion: 'What information remains the same?',
    inferenceChoices: ['Pickup time', 'The weather forecast', 'The building name', 'The sport being played'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'The announcement says the pickup time does not change.',
    tags: ['weather', 'community', 'announcement'],
  },
  {
    id: 'market-vendor',
    objectiveCode: 'L-11',
    difficulty: 2,
    script:
      'Hoy tenemos mangos, aguacates y cilantro fresco. Si compra dos libras de tomates, le damos una bolsa pequena de limones sin costo adicional hasta las dos de la tarde.',
    mainQuestion: 'What is the vendor offering?',
    mainChoices: ['A produce promotion', 'A cooking class', 'A furniture sale', 'A concert ticket'],
    mainCorrectIndex: 0,
    mainExplanation: 'The speaker lists produce and offers free lemons with tomato purchases.',
    inferenceQuestion: 'When does the special offer end?',
    inferenceChoices: ['At 2:00 p.m.', 'At sunrise', 'Next Monday', 'After dinner'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'The vendor says the offer lasts until two in the afternoon.',
    tags: ['market', 'food', 'numbers'],
  },
  {
    id: 'teacher-feedback',
    objectiveCode: 'L-12',
    difficulty: 4,
    script:
      'Tu presentacion fue clara y bien organizada. Para mejorarla, anade una conclusion que conecte tus ejemplos con la idea principal y practica un ritmo un poco mas pausado.',
    mainQuestion: 'What is the speaker mainly doing?',
    mainChoices: ['Giving feedback on a presentation', 'Rejecting a class proposal', 'Announcing a field trip', 'Explaining cafeteria rules'],
    mainCorrectIndex: 0,
    mainExplanation: 'The speaker praises the presentation and suggests specific improvements.',
    inferenceQuestion: 'Which improvement is recommended?',
    inferenceChoices: ['Add a stronger conclusion', 'Use fewer examples entirely', 'Speak much faster', 'Change the topic to food'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'The speaker recommends connecting examples to the main idea in the conclusion.',
    tags: ['feedback', 'classroom', 'communication'],
  },
  {
    id: 'radio-volunteer',
    objectiveCode: 'L-13',
    difficulty: 3,
    script:
      'La radio local busca voluntarios bilingues para leer anuncios comunitarios los domingos. No se necesita experiencia previa, pero si disponibilidad por la manana y buena pronunciacion.',
    mainQuestion: 'What is the radio station seeking?',
    mainChoices: ['Bilingual volunteers', 'Professional singers only', 'Bus drivers', 'Restaurant reviewers'],
    mainCorrectIndex: 0,
    mainExplanation: 'The station seeks bilingual volunteers to read community announcements.',
    inferenceQuestion: 'Which qualification matters for the role?',
    inferenceChoices: ['Morning availability', 'A medical license', 'Experience as a pilot', 'Owning a restaurant'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'The announcement says no prior experience is needed, but morning availability and good pronunciation are required.',
    tags: ['volunteer', 'community', 'language'],
  },
  {
    id: 'bus-detour',
    objectiveCode: 'L-14',
    difficulty: 4,
    script:
      'Por reparaciones en la calle Central, la ruta doce no parara frente al parque esta semana. Los pasajeros deben usar la parada temporal en la avenida Robles, junto a la farmacia.',
    mainQuestion: 'What is the announcement about?',
    mainChoices: ['A bus route detour', 'A park renovation vote', 'A new pharmacy opening', 'A school exam schedule'],
    mainCorrectIndex: 0,
    mainExplanation: 'The route will not stop in its usual place because of street repairs.',
    inferenceQuestion: 'Where should passengers wait?',
    inferenceChoices: ['At the temporary stop near the pharmacy', 'Inside the park office', 'At the airport terminal', 'Behind the school cafeteria'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'Passengers are told to use the temporary stop on Robles Avenue next to the pharmacy.',
    tags: ['transportation', 'directions', 'public announcement'],
  },
  {
    id: 'club-meeting',
    objectiveCode: 'L-15',
    difficulty: 2,
    script:
      'El club de conversacion en espanol se reunira el jueves en la sala de arte, no en la biblioteca. El tema sera como pedir direcciones y describir lugares del barrio.',
    mainQuestion: 'What meeting is announced?',
    mainChoices: ['A Spanish conversation club', 'A math tutoring session', 'A library board meeting', 'A basketball practice'],
    mainCorrectIndex: 0,
    mainExplanation: 'The announcement names a Spanish conversation club and its topic.',
    inferenceQuestion: 'What language function will participants practice?',
    inferenceChoices: ['Asking for directions', 'Writing legal contracts', 'Discussing chemistry formulas', 'Repairing bicycles'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'The topic includes asking for directions and describing neighborhood places.',
    tags: ['language learning', 'directions', 'school'],
  },
  {
    id: 'field-trip',
    objectiveCode: 'L-16',
    difficulty: 3,
    script:
      'Recuerden traer permiso firmado, almuerzo y una chaqueta ligera para la excursion al jardin botanico. Saldremos de la escuela a las ocho en punto, aunque llueva.',
    mainQuestion: 'Where is the class going?',
    mainChoices: ['To a botanical garden', 'To a movie theater', 'To a city hall meeting', 'To a bakery'],
    mainCorrectIndex: 0,
    mainExplanation: 'The speaker mentions a field trip to the botanical garden.',
    inferenceQuestion: 'Why should students bring a light jacket?',
    inferenceChoices: ['They may be outside in changing weather.', 'They will enter a freezer.', 'The school uniform changed.', 'They are selling jackets.'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'The trip is outdoors and will happen even if it rains, so a light jacket is practical.',
    tags: ['school', 'field trip', 'weather'],
  },
  {
    id: 'apartment-message',
    objectiveCode: 'L-17',
    difficulty: 4,
    script:
      'Buenos dias, vecinos. Manana cortaremos el agua de nueve a once para reparar una tuberia. Por favor llenen recipientes esta noche y no usen la lavadora durante ese horario.',
    mainQuestion: 'What service interruption is announced?',
    mainChoices: ['Water will be shut off.', 'Electricity will be shut off.', 'Internet will be upgraded.', 'Garbage pickup is canceled.'],
    mainCorrectIndex: 0,
    mainExplanation: 'The speaker says water will be shut off from nine to eleven for pipe repairs.',
    inferenceQuestion: 'What should residents do beforehand?',
    inferenceChoices: ['Fill containers with water', 'Move their cars', 'Pay rent early', 'Close all email accounts'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'Residents are asked to fill containers the night before.',
    tags: ['housing', 'announcement', 'daily life'],
  },
  {
    id: 'student-absence',
    objectiveCode: 'L-18',
    difficulty: 3,
    script:
      'Profesora, soy Elena. No pude asistir hoy porque mi hermano tuvo una cita medica. Ya le pedi a Ana las notas, y manana le entregare la tarea que debia hoy.',
    mainQuestion: 'Why was Elena absent?',
    mainChoices: ['Her brother had a medical appointment.', 'She missed the bus to a game.', 'She was taking a vacation.', 'Her class was canceled.'],
    mainCorrectIndex: 0,
    mainExplanation: 'Elena explains that she missed class because of her brother medical appointment.',
    inferenceQuestion: 'What has Elena done to keep up with class?',
    inferenceChoices: ['Asked Ana for the notes', 'Changed schools', 'Asked for a lower grade', 'Canceled the assignment'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'Elena says she already asked Ana for the class notes.',
    tags: ['school', 'absence', 'responsibility'],
  },
  {
    id: 'workshop-signup',
    objectiveCode: 'L-19',
    difficulty: 4,
    script:
      'El taller sobre solicitudes de becas tendra cupo limitado. Para reservar un lugar, envie su nombre y grado escolar antes del viernes. Los estudiantes de ultimo ano tendran prioridad.',
    mainQuestion: 'What is the workshop about?',
    mainChoices: ['Scholarship applications', 'Cooking techniques', 'Driver safety', 'Museum cataloging'],
    mainCorrectIndex: 0,
    mainExplanation: 'The workshop focuses on scholarship applications.',
    inferenceQuestion: 'Who will receive priority?',
    inferenceChoices: ['Final-year students', 'Only teachers', 'Parents of preschoolers', 'People who arrive late'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'The announcement says final-year students will have priority.',
    tags: ['education', 'scholarships', 'announcement'],
  },
  {
    id: 'lost-item',
    objectiveCode: 'L-20',
    difficulty: 1,
    script:
      'Se encontro una mochila azul en la cafeteria despues del almuerzo. Tiene un cuaderno de matematicas y una botella roja. El dueno puede recogerla en la oficina principal.',
    mainQuestion: 'What item was found?',
    mainChoices: ['A blue backpack', 'A red bicycle', 'A math textbook order', 'A cafeteria table'],
    mainCorrectIndex: 0,
    mainExplanation: 'The announcement says a blue backpack was found in the cafeteria.',
    inferenceQuestion: 'Where should the owner go?',
    inferenceChoices: ['The main office', 'The gym', 'The bus stop', 'The library basement'],
    inferenceCorrectIndex: 0,
    inferenceExplanation: 'The owner can pick up the backpack in the main office.',
    tags: ['school', 'lost item', 'detail'],
  },
];
