import type { PromptFamily } from './writingPrompts';

export const oralPromptFamilies: PromptFamily[] = [
  {
    id: 'school-message',
    objectiveCode: 'O-01',
    difficulty: 2,
    context: 'Speak in Spanish as if leaving a clear school-related voice message.',
    tasks: [
      'confirm a conference time and mention one topic for discussion',
      'explain a schedule change for a club meeting',
      'invite a family to a classroom event',
      'remind students what to bring for an excursion',
      'describe where to find a lost item at school',
    ],
    tags: ['oral', 'school communication', 'clarity'],
  },
  {
    id: 'classroom-instruction',
    objectiveCode: 'O-02',
    difficulty: 3,
    context: 'Speak in Spanish to give classroom directions.',
    tasks: [
      'explain how to work with a partner during a reading task',
      'give step-by-step instructions for a short writing activity',
      'tell students how to prepare for a listening exercise',
      'explain how to use an accent toolbar while writing',
      'guide students through a respectful peer-feedback routine',
    ],
    tags: ['oral', 'classroom', 'commands'],
  },
  {
    id: 'personal-opinion',
    objectiveCode: 'O-03',
    difficulty: 3,
    context: 'Speak in Spanish for one minute giving an opinion.',
    tasks: [
      'explain whether daily practice is more useful than occasional long study sessions',
      'recommend a community event and give two reasons',
      'explain why reading authentic texts can help language learners',
      'describe the value of learning regional language variation',
      'recommend a way to reduce stress before an exam',
    ],
    tags: ['oral', 'opinion', 'support'],
  },
  {
    id: 'cultural-explanation',
    objectiveCode: 'O-04',
    difficulty: 4,
    context: 'Speak in Spanish to explain a cultural topic thoughtfully.',
    tasks: [
      'explain why one tradition can vary among families',
      'describe how public art can preserve community memory',
      'explain how music can reflect migration or identity',
      'compare formal and informal address forms in context',
      'explain why stereotypes weaken cultural understanding',
    ],
    tags: ['oral', 'culture', 'analysis'],
  },
  {
    id: 'problem-solving',
    objectiveCode: 'O-05',
    difficulty: 3,
    context: 'Speak in Spanish to solve a practical communication problem.',
    tasks: [
      'ask for clarification about an assignment deadline',
      'explain politely that you need to reschedule a meeting',
      'ask a librarian for help finding a resource',
      'tell a colleague how you handled a misunderstanding',
      'give advice to a student who missed class',
    ],
    tags: ['oral', 'problem solving', 'pragmatics'],
  },
  {
    id: 'storytelling',
    objectiveCode: 'O-06',
    difficulty: 4,
    context: 'Speak in Spanish using narration and description.',
    tasks: [
      'describe a visit to a community festival',
      'tell what happened when a class plan changed because of weather',
      'describe a successful group project from beginning to end',
      'narrate how someone prepared for a presentation',
      'describe a meaningful conversation with a family member or mentor',
    ],
    tags: ['oral', 'narration', 'past tenses'],
  },
  {
    id: 'professional-register',
    objectiveCode: 'O-07',
    difficulty: 5,
    context: 'Speak in Spanish using a professional or academic register.',
    tasks: [
      'summarize a student progress concern with tact and specificity',
      'explain the goals of a bilingual literacy activity to colleagues',
      'present a brief plan for inclusive cultural comparison',
      'justify the use of rubrics for writing and oral practice',
      'explain how local data can guide daily practice without a server',
    ],
    tags: ['oral', 'register', 'professional communication'],
  },
];
