export interface ReadingSeed {
  id: string;
  objectiveCode: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  passage: string;
  mainQuestion: string;
  mainChoices: string[];
  mainCorrectIndex: number;
  mainExplanation: string;
  detailQuestion: string;
  detailChoices: string[];
  detailCorrectIndex: number;
  detailExplanation: string;
  tags: string[];
}

export const readingPassageSeeds: ReadingSeed[] = [
  {
    id: 'parent-email',
    objectiveCode: 'R-01',
    difficulty: 2,
    passage:
      'Estimada profesora Martin: Gracias por avisarme sobre el proyecto de ciencias. Sofia esta emocionada, pero necesita aclarar si puede usar fotos de plantas del jardin de su abuela. Tambien quisiera saber si la presentacion debe durar tres o cinco minutos. Atentamente, Laura Perez.',
    mainQuestion: 'What is the purpose of the email?',
    mainChoices: ['To ask questions about a science project', 'To complain about cafeteria food', 'To request a bus schedule', 'To apply for a teaching job'],
    mainCorrectIndex: 0,
    mainExplanation: 'The parent asks two practical questions about Sofia science project.',
    detailQuestion: 'What does Sofia want to use?',
    detailChoices: ['Photos of plants from her grandmother garden', 'A video from a commercial website', 'A map of the subway', 'An interview with the principal'],
    detailCorrectIndex: 0,
    detailExplanation: 'The email asks whether Sofia can use photos of plants from her grandmother garden.',
    tags: ['email', 'school', 'detail'],
  },
  {
    id: 'community-board',
    objectiveCode: 'R-02',
    difficulty: 3,
    passage:
      'Aviso comunitario: El sabado se pintara un mural en la pared norte del centro juvenil. Los participantes deben llevar ropa comoda. Los materiales seran proporcionados por la organizacion Vecinos Unidos, y un artista local guiara el diseno.',
    mainQuestion: 'What is the notice about?',
    mainChoices: ['A community mural project', 'A private art sale', 'A soccer tournament', 'A public transportation strike'],
    mainCorrectIndex: 0,
    mainExplanation: 'The notice invites people to help paint a mural at the youth center.',
    detailQuestion: 'What will the organization provide?',
    detailChoices: ['Materials', 'Dinner reservations', 'School uniforms', 'Bus tickets'],
    detailCorrectIndex: 0,
    detailExplanation: 'Vecinos Unidos will provide the materials for the mural.',
    tags: ['community', 'art', 'announcement'],
  },
  {
    id: 'school-handbook',
    objectiveCode: 'R-03',
    difficulty: 4,
    passage:
      'Segun la guia escolar, los estudiantes que lleguen tarde deben presentarse primero en la oficina para recibir un pase. Esta medida no busca castigar, sino asegurar que la asistencia se registre correctamente y que las familias reciban informacion precisa.',
    mainQuestion: 'What is the policy mainly intended to ensure?',
    mainChoices: ['Accurate attendance records', 'More homework', 'Longer lunch periods', 'A new grading scale'],
    mainCorrectIndex: 0,
    mainExplanation: 'The passage says the purpose is to record attendance correctly and inform families accurately.',
    detailQuestion: 'What must late students obtain?',
    detailChoices: ['A pass from the office', 'A library card', 'A new uniform', 'A parking permit'],
    detailCorrectIndex: 0,
    detailExplanation: 'Late students must go to the office first to receive a pass.',
    tags: ['school policy', 'inference', 'detail'],
  },
  {
    id: 'cultural-note',
    objectiveCode: 'R-04',
    difficulty: 4,
    passage:
      'En muchas comunidades andinas, los mercados semanales cumplen una funcion economica y social. Ademas de comprar alimentos, las personas intercambian noticias, mantienen redes familiares y preservan practicas linguisticas locales.',
    mainQuestion: 'What is the main idea of the passage?',
    mainChoices: ['Markets can serve economic, social, and linguistic functions.', 'Markets are used only by tourists.', 'Weekly markets have disappeared everywhere.', 'Andean communities avoid family networks.'],
    mainCorrectIndex: 0,
    mainExplanation: 'The passage explains several roles of weekly markets beyond buying food.',
    detailQuestion: 'Which practice is mentioned as being preserved?',
    detailChoices: ['Local linguistic practices', 'Professional baseball rules', 'Ocean navigation', 'Factory accounting'],
    detailCorrectIndex: 0,
    detailExplanation: 'The passage says markets help preserve local linguistic practices.',
    tags: ['culture', 'Andes', 'community'],
  },
  {
    id: 'classroom-text',
    objectiveCode: 'R-05',
    difficulty: 2,
    passage:
      'Para escribir una buena descripcion, observa primero los detalles importantes. Luego organiza tus ideas de lo general a lo especifico. Finalmente, revisa los adjetivos para que concuerden con los sustantivos.',
    mainQuestion: 'What skill does the text teach?',
    mainChoices: ['Writing a description', 'Solving equations', 'Buying groceries', 'Reading a bus map'],
    mainCorrectIndex: 0,
    mainExplanation: 'The text gives steps for writing a good description.',
    detailQuestion: 'What should be checked at the end?',
    detailChoices: ['Adjective agreement', 'The price of paper', 'The room temperature', 'The author birthday'],
    detailCorrectIndex: 0,
    detailExplanation: 'The final step is reviewing adjectives so they agree with nouns.',
    tags: ['writing', 'grammar', 'classroom'],
  },
  {
    id: 'museum-label',
    objectiveCode: 'R-06',
    difficulty: 4,
    passage:
      'Esta pieza de ceramica fue creada por una cooperativa de artesanas que combina tecnicas tradicionales con disenos contemporaneos. La venta de estas obras apoya talleres de formacion para jovenes de la region.',
    mainQuestion: 'What does the label emphasize?',
    mainChoices: ['A blend of tradition, contemporary design, and community support', 'A competition between museums', 'A ban on handmade objects', 'A recipe for regional food'],
    mainCorrectIndex: 0,
    mainExplanation: 'The label highlights traditional techniques, contemporary designs, and support for youth workshops.',
    detailQuestion: 'What does the sale of the pieces support?',
    detailChoices: ['Training workshops for young people', 'Airline discounts', 'A new soccer stadium', 'Private language exams'],
    detailCorrectIndex: 0,
    detailExplanation: 'The passage says sales support training workshops for regional youth.',
    tags: ['museum', 'culture', 'art'],
  },
  {
    id: 'student-note',
    objectiveCode: 'R-07',
    difficulty: 1,
    passage:
      'Carlos: Te deje el libro de historia en la mesa de la cocina. Lee las paginas 42 a 47 antes de la clase. Mama',
    mainQuestion: 'What is the note about?',
    mainChoices: ['A reading assignment', 'A party invitation', 'A lost passport', 'A restaurant bill'],
    mainCorrectIndex: 0,
    mainExplanation: 'The note tells Carlos where the history book is and what pages to read.',
    detailQuestion: 'Where is the book?',
    detailChoices: ['On the kitchen table', 'Under the bed', 'In the car', 'At the library desk'],
    detailCorrectIndex: 0,
    detailExplanation: 'The note says the book is on the kitchen table.',
    tags: ['family', 'school', 'note'],
  },
  {
    id: 'recipe-intro',
    objectiveCode: 'R-08',
    difficulty: 2,
    passage:
      'Esta sopa de lentejas se prepara con ingredientes sencillos y se adapta facilmente a lo que haya en casa. Si no tiene zanahorias, puede usar calabaza. Lo importante es cocinar las lentejas hasta que esten tiernas.',
    mainQuestion: 'What does the passage suggest about the recipe?',
    mainChoices: ['It is flexible and uses simple ingredients.', 'It requires expensive equipment.', 'It must be served cold.', 'It is only for professional chefs.'],
    mainCorrectIndex: 0,
    mainExplanation: 'The passage says the soup uses simple ingredients and can be adapted.',
    detailQuestion: 'What can replace carrots?',
    detailChoices: ['Squash', 'Rice paper', 'Coffee', 'Cheese only'],
    detailCorrectIndex: 0,
    detailExplanation: 'The passage says squash can be used if carrots are unavailable.',
    tags: ['food', 'instructions', 'daily life'],
  },
  {
    id: 'student-council',
    objectiveCode: 'R-09',
    difficulty: 3,
    passage:
      'El consejo estudiantil propone abrir la biblioteca durante el almuerzo dos dias por semana. La meta es ofrecer un espacio tranquilo para estudiar, leer o recibir ayuda breve de tutores voluntarios.',
    mainQuestion: 'What is the proposal?',
    mainChoices: ['Open the library during lunch twice a week', 'Close the cafeteria permanently', 'Replace all tutors with videos', 'Shorten the school year'],
    mainCorrectIndex: 0,
    mainExplanation: 'The proposal is to open the library at lunch two days per week.',
    detailQuestion: 'Why does the council propose this?',
    detailChoices: ['To provide a quiet space and tutoring help', 'To sell more lunches', 'To cancel reading assignments', 'To move all classes online'],
    detailCorrectIndex: 0,
    detailExplanation: 'The purpose is study, reading, and brief help from volunteer tutors.',
    tags: ['school', 'proposal', 'community'],
  },
  {
    id: 'short-biography',
    objectiveCode: 'R-10',
    difficulty: 4,
    passage:
      'La poeta escribio durante una epoca de cambios politicos. Aunque sus primeros textos hablaban de la vida familiar, sus obras posteriores exploraron la memoria colectiva y la responsabilidad civica.',
    mainQuestion: 'How did the poet work change?',
    mainChoices: ['It moved from family themes toward collective memory and civic responsibility.', 'It became only humorous advertisements.', 'It stopped using written language.', 'It focused exclusively on weather reports.'],
    mainCorrectIndex: 0,
    mainExplanation: 'The passage contrasts early family themes with later civic and collective concerns.',
    detailQuestion: 'What historical context is mentioned?',
    detailChoices: ['A period of political change', 'A famous sports season', 'The invention of the telephone', 'A drought in a desert town'],
    detailCorrectIndex: 0,
    detailExplanation: 'The poet wrote during a time of political changes.',
    tags: ['literature', 'culture', 'inference'],
  },
  {
    id: 'environment-notice',
    objectiveCode: 'R-11',
    difficulty: 3,
    passage:
      'Para reducir el desperdicio, la escuela instalara estaciones de agua donde los estudiantes podran llenar botellas reutilizables. Las botellas desechables seguiran permitidas durante las excursiones largas.',
    mainQuestion: 'What is the school trying to reduce?',
    mainChoices: ['Waste', 'Attendance', 'Reading time', 'Parent meetings'],
    mainCorrectIndex: 0,
    mainExplanation: 'The notice says the water stations are intended to reduce waste.',
    detailQuestion: 'When are disposable bottles still allowed?',
    detailChoices: ['During long field trips', 'Only during exams', 'Every morning meeting', 'Never under any condition'],
    detailCorrectIndex: 0,
    detailExplanation: 'Disposable bottles remain allowed for long field trips.',
    tags: ['environment', 'school', 'policy'],
  },
  {
    id: 'book-club',
    objectiveCode: 'R-12',
    difficulty: 2,
    passage:
      'El club de lectura eligio una novela corta para que todos puedan terminarla antes de la reunion. Cada participante debe traer una pregunta abierta que invite a conversar, no solo a recordar datos.',
    mainQuestion: 'Why did the club choose a short novel?',
    mainChoices: ['So everyone can finish it before the meeting', 'So nobody has to read', 'So the librarian can close early', 'So the book can be sold online'],
    mainCorrectIndex: 0,
    mainExplanation: 'The passage says a short novel helps everyone finish before the meeting.',
    detailQuestion: 'What kind of question should participants bring?',
    detailChoices: ['An open-ended discussion question', 'A math equation', 'A question with no relation to the book', 'A list of prices'],
    detailCorrectIndex: 0,
    detailExplanation: 'Participants should bring a question that invites conversation, not mere recall.',
    tags: ['reading', 'discussion', 'school'],
  },
  {
    id: 'health-brochure',
    objectiveCode: 'R-13',
    difficulty: 3,
    passage:
      'Dormir lo suficiente ayuda a la concentracion y al estado de animo. Para crear una rutina, apague las pantallas treinta minutos antes de acostarse y mantenga una hora regular para dormir, incluso los fines de semana.',
    mainQuestion: 'What is the brochure mainly recommending?',
    mainChoices: ['Healthy sleep habits', 'A new phone plan', 'Weekend travel', 'A music class'],
    mainCorrectIndex: 0,
    mainExplanation: 'The brochure gives advice for a consistent sleep routine.',
    detailQuestion: 'What should readers do before bedtime?',
    detailChoices: ['Turn off screens thirty minutes before bed', 'Drink coffee', 'Start homework at midnight', 'Open all windows in winter'],
    detailCorrectIndex: 0,
    detailExplanation: 'The text recommends turning off screens thirty minutes before going to bed.',
    tags: ['health', 'routine', 'advice'],
  },
  {
    id: 'work-email',
    objectiveCode: 'R-14',
    difficulty: 4,
    passage:
      'Equipo: La reunion del martes sera breve. Revisaremos los comentarios de los clientes, escogeremos dos prioridades y dejaremos los temas tecnicos para el jueves, cuando pueda asistir el especialista.',
    mainQuestion: 'What will the team do Tuesday?',
    mainChoices: ['Review customer comments and choose priorities', 'Discuss every technical issue', 'Cancel the Thursday meeting', 'Train a new specialist'],
    mainCorrectIndex: 0,
    mainExplanation: 'Tuesday is for customer comments and two priorities; technical topics are postponed.',
    detailQuestion: 'Why are technical topics delayed?',
    detailChoices: ['The specialist can attend Thursday.', 'The clients rejected them.', 'The room is too small.', 'The team lost the documents.'],
    detailCorrectIndex: 0,
    detailExplanation: 'Technical topics will wait until Thursday when the specialist can attend.',
    tags: ['workplace', 'email', 'schedule'],
  },
  {
    id: 'historical-plaque',
    objectiveCode: 'R-15',
    difficulty: 5,
    passage:
      'Esta plaza fue durante decadas un punto de encuentro para vendedores, musicos y familias recien llegadas. Su valor historico no reside solo en los edificios, sino en las relaciones comunitarias que alli se formaron.',
    mainQuestion: 'What does the plaque emphasize about the plaza?',
    mainChoices: ['Its community relationships as well as its buildings', 'Its lack of public use', 'Its role as an airport', 'Its value only as private property'],
    mainCorrectIndex: 0,
    mainExplanation: 'The plaque says the historical value includes the relationships formed there, not only buildings.',
    detailQuestion: 'Who is mentioned as using the plaza?',
    detailChoices: ['Vendors, musicians, and newly arrived families', 'Only government officials', 'Only tourists with tickets', 'Pilots and engineers'],
    detailCorrectIndex: 0,
    detailExplanation: 'The passage lists vendors, musicians, and newly arrived families.',
    tags: ['history', 'community', 'culture'],
  },
  {
    id: 'class-rubric',
    objectiveCode: 'R-16',
    difficulty: 3,
    passage:
      'En el ensayo comparativo, una calificacion alta requiere una tesis clara, ejemplos especificos de ambos textos y transiciones que expliquen la relacion entre las ideas. La extension por si sola no garantiza una nota alta.',
    mainQuestion: 'What does the rubric value most?',
    mainChoices: ['Clear argument, specific examples, and logical transitions', 'Length alone', 'Decorative drawings', 'Memorized definitions only'],
    mainCorrectIndex: 0,
    mainExplanation: 'The rubric names thesis, examples from both texts, and transitions as important.',
    detailQuestion: 'What does not guarantee a high score?',
    detailChoices: ['Length by itself', 'Using examples', 'Having a thesis', 'Explaining relationships'],
    detailCorrectIndex: 0,
    detailExplanation: 'The passage explicitly says length alone does not guarantee a high grade.',
    tags: ['writing', 'rubric', 'school'],
  },
  {
    id: 'garden-sign',
    objectiveCode: 'R-17',
    difficulty: 2,
    passage:
      'Bienvenidos al jardin escolar. Pueden observar las plantas, pero no corten hojas ni flores. Los grupos deben permanecer en los senderos para proteger las raices.',
    mainQuestion: 'What is the sign mainly about?',
    mainChoices: ['Rules for protecting the school garden', 'How to buy flowers', 'A new sports schedule', 'A cafeteria menu'],
    mainCorrectIndex: 0,
    mainExplanation: 'The sign gives rules to protect plants and roots.',
    detailQuestion: 'Why should groups stay on paths?',
    detailChoices: ['To protect roots', 'To avoid reading signs', 'To find the bus faster', 'To water the cafeteria floor'],
    detailCorrectIndex: 0,
    detailExplanation: 'The sign says staying on paths protects roots.',
    tags: ['environment', 'school', 'rules'],
  },
  {
    id: 'festival-program',
    objectiveCode: 'R-18',
    difficulty: 3,
    passage:
      'Programa del festival: A las dos habra narracion oral para ninos. A las cuatro, un panel de escritores locales discutira como las historias familiares influyen en sus obras. La entrada es gratuita.',
    mainQuestion: 'What does the festival include?',
    mainChoices: ['Storytelling and a writers panel', 'A medical clinic', 'A driving test', 'A private auction only'],
    mainCorrectIndex: 0,
    mainExplanation: 'The program includes oral storytelling and a panel of local writers.',
    detailQuestion: 'What will the writers discuss?',
    detailChoices: ['How family stories influence their work', 'How to repair cars', 'How to file taxes', 'How to change a flight'],
    detailCorrectIndex: 0,
    detailExplanation: 'The panel topic is how family stories influence the writers works.',
    tags: ['festival', 'literature', 'culture'],
  },
  {
    id: 'teacher-message',
    objectiveCode: 'R-19',
    difficulty: 4,
    passage:
      'Si un estudiante no entiende una palabra durante la lectura, no debe detenerse automaticamente. Primero puede usar pistas del contexto, observar prefijos o sufijos y luego confirmar el significado con un diccionario.',
    mainQuestion: 'What reading strategy is recommended?',
    mainChoices: ['Use context and word parts before checking a dictionary', 'Stop reading whenever a word is unfamiliar', 'Translate every word aloud immediately', 'Avoid dictionaries completely'],
    mainCorrectIndex: 0,
    mainExplanation: 'The message recommends context clues, prefixes, suffixes, and then dictionary confirmation.',
    detailQuestion: 'Which word parts are mentioned?',
    detailChoices: ['Prefixes and suffixes', 'Only vowels', 'Rhymes only', 'Capital letters only'],
    detailCorrectIndex: 0,
    detailExplanation: 'The passage names prefixes and suffixes as useful clues.',
    tags: ['reading strategy', 'language', 'classroom'],
  },
  {
    id: 'neighborhood-profile',
    objectiveCode: 'R-20',
    difficulty: 5,
    passage:
      'El barrio cambio con la llegada del tren, pero sus residentes no fueron observadores pasivos. Organizaron comites, negociaron horarios seguros para cruzar las vias y defendieron espacios publicos para los jovenes.',
    mainQuestion: 'What is the passage main point?',
    mainChoices: ['Residents actively shaped changes brought by the train.', 'The train removed all community activity.', 'Young people avoided public spaces.', 'The neighborhood had no organized groups.'],
    mainCorrectIndex: 0,
    mainExplanation: 'The passage stresses that residents organized and negotiated rather than passively accepting change.',
    detailQuestion: 'What did residents negotiate?',
    detailChoices: ['Safe times to cross the tracks', 'Airline seating charts', 'The price of textbooks', 'A private concert schedule'],
    detailCorrectIndex: 0,
    detailExplanation: 'Residents negotiated safe schedules for crossing the train tracks.',
    tags: ['community', 'history', 'inference'],
  },
];
